run_name: "mistral_7b_sft_clinical_codes_v1"
base_model: "mistralai/Mistral-7B-Instruct-v0.2"

dataset_path: "data/input/patient_notes_dataset.jsonl"
output_dir: "data/output/models/"

training_args:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  num_train_epochs: 3
  learning_rate: 2.0e-4
  fp16: True
  logging_steps: 10
  save_total_limit: 2
  optim: "paged_adamw_8bit"
  save_strategy: "epoch"

peft_config:
  lora_alpha: 16
  lora_dropout: 0.1
  r: 64
  bias: "none"
  task_type: "CAUSAL_LM"

quantization_config:
  load_in_4bit: True
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_compute_dtype: torch.bfloat16
  bnb_4bit_use_double_quant: False
